#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	Script to control prefered apps to launch for all themes
#	Author: z0mbi3
#	url:    https://github.com/gh0stzk/dotfiles

WIDGET_DIR="$HOME/.config/eww"

case "$1" in
	--menu)
		rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi
		;;
	--rice)
		~/.config/bspwm/src/RiceSelector
		;;
	--terminal)
		~/.config/bspwm/src/Term --terminal
		;;
	--floating)
		~/.config/bspwm/src/Term --floating
		;;
	--update)
		~/.config/bspwm/src/Term --update
		;;
	--checkupdates)
		~/.config/bspwm/src/Term --checkupdates
		;;
	--netmanager)
		~/.config/bspwm/src/NetManagerDM
		;;
	--bluetooth)
		~/.config/bspwm/src/rofi-bluetooth
		;;
	--clipboard)
		clipcat-menu
		;;
	--screenshot)
		ScreenShoTer
		;;
	--powermenu)
		~/.config/bspwm/src/PowerMenu
		;;
	--android)
		AndroidMount
		;;
	--keyboard)
		KeyBoardL
		;;
	--yazi)
		~/.config/bspwm/src/Term --yazi
		;;
	--nvim)
		~/.config/bspwm/src/Term --nvim
		;;
	--music)
		~/.config/bspwm/src/Term --music
		;;
	--fetch)
		~/.config/bspwm/src/Term --fetch
		;;
	--scratch)
		~/.config/bspwm/src/Term --scratch
		;;
	--yaziscratch)
		~/.config/bspwm/src/Term --yaziscratch
		;;
		# Apps
	--filemanager)
		thunar
		;;
	--browser)
		firefox
		;;
	--editor)
		geany
		;;
	--telegram)
		telegram-desktop
		;;
	--whats)
		firefox -new-tab https://web.whatsapp.com/
		;;
	--soundcontrol)
		pavucontrol
		;;
		# Eww Widgets
	--KeyHelp)
		eww -c "$WIDGET_DIR" open --toggle csheet
		;;
	--usercard)
		eww -c "$WIDGET_DIR" open --toggle launchermenu
		;;
	--player)
		eww -c "$WIDGET_DIR" open --toggle music
		;;
	--calendar)
		eww -c "$WIDGET_DIR" open --toggle date
		;;
	*)
		echo "Invalid Option"
		;;
esac
