#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X
# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 15


#bspc config border_width         3
#bspc config window_gap          8

bspc config split_ratio          0.61
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child



bspc rule -a Blueman-manager state=floating
bspc rule -a AmneziaVPN state=floating
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen  --restore &
dunst &
polybar &
xautolock -time 30 -locker "$HOME/.config/bspwm/src/ScreenLocker" &

