#!/bin/env bash

choice=$(printf "Выход\nПерезагрузка\nВыключение" | rofi -dmenu)
case "$choice" in
  Блокировка) sh ~/.config/polybar/scripts/screen-lock ;;
  Выход) pkill -KILL -u "$USER" ;;
  Перезагрузка) systemctl reboot ;;
  Выключение) systemctl poweroff ;;
esac