#!/bin/env bash

choice=$(printf "Блокировка\nПерезагрузка\nВыключение" | rofi -dmenu)
case "$choice" in
  Блокировка) /home/dendrey/.config/bspwm/src/ScreenLocker;;
  Выход)  sudo systemctl restart display-manager ;;
  Перезагрузка) systemctl reboot ;;
  Выключение) systemctl poweroff ;;
esac
