#!/bin/bash

# Проверяем, есть ли окно blueman-manager
if xdotool search --onlyvisible --class "Blueman-manager" >/dev/null 2>&1; then
    # Если есть, закрываем
    xdotool search --onlyvisible --class "Blueman-manager" windowkill %@ 
else
    # Если нет, запускаем
    blueman-manager
fi
